window.jewelryDataset = [
  {
    id: 1,
    title: "Золотое кольцо с бриллиантом",
    price: 28500,
    category: "Кольца",
    image: "img/item3/img1.jpg",
  },
  {
    id: 2,
    title: "Серебряные серьги с жемчугом",
    price: 12400,
    category: "Серьги",
    image: "img/item3/img2.jpg",
  },
  {
    id: 3,
    title: "Платиновое обручальное кольцо",
    price: 43200,
    category: "Кольца",
    image: "img/item3/img3.jpg",
  },
  {
    id: 4,
    title: "Золотой браслет с гравировкой",
    price: 36700,
    category: "Браслеты",
    image: "img/item3/img4.jpg",
  },
  {
    id: 5,
    title: "Серьги с изумрудом в золоте",
    price: 28900,
    category: "Серьги",
    image: "img/item3/img5.jpg",
  },
  {
    id: 6,
    title: "Колье из белого золота с сапфиром",
    price: 54100,
    category: "Колье",
    image: "img/item3/img6.jpg",
  },
  {
    id: 7,
    title: "Мужской серебряный перстень",
    price: 18700,
    category: "Кольца",
    image: "img/item3/img7.jpg",
  },
  {
    id: 8,
    title: "Подвеска с бриллиантом в платине",
    price: 62300,
    category: "Подвески",
    image: "img/item3/img8.jpg",
  },
  {
    id: 9,
    title: "Теннисный браслет из золота",
    price: 45800,
    category: "Браслеты",
    image: "img/item3/img9.jpg",
  },
  {
    id: 10,
    title: "Серьги-гвоздики с рубином",
    price: 32500,
    category: "Серьги",
    image: "img/item3/img10.jpg",
  },
  {
    id: 11,
    title: "Колье жемчужное классическое",
    price: 27800,
    category: "Колье",
    image: "img/item3/img11.jpg",
  },
  {
    id: 12,
    title: "Обручальное кольцо с гравировкой",
    price: 15600,
    category: "Кольца",
    image: "img/item3/img12.jpg",
  },
  {
    id: 13,
    title: "Браслет плетеный из серебра",
    price: 14200,
    category: "Браслеты",
    image: "img/item3/img13.jpg",
  },
  {
    id: 14,
    title: "Серьги-кисти с цирконием",
    price: 19800,
    category: "Серьги",
    image: "img/item3/img14.jpg",
  },
  {
    id: 15,
    title: "Колье-чокер с подвеской",
    price: 23400,
    category: "Колье",
    image: "img/item3/img15.jpg",
  },
  {
    id: 16,
    title: "Комплект: кольца и колье",
    price: 67200,
    category: "Комплекты",
    image: "img/item3/img16.jpg",
  },
];
